id: ID6876F7A
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3880-final
source_file: null
initial_creation_type: input
imported: '2022-08-08T09:36:36.829019'
last_modified: '2022-08-08T09:36:36.829031'
parser: null
source_metadata:
  title: Commentary
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
ocr_word_median_confidence_index: null
base: {}
